### ISSUE TITLE
Section Discoverability of repository dans Les Gens

### ISSUE THREAD

**Issue by decima** [takk74/OpenSourcePourLesNuls#11]
Peut-être cette discoverability devrait être plus dans une section social non? C'est propre a Github cette mécanique

**Comment by ZPyrolink** [comment]
Merci pour votre retour.
Depuis la création de votre Issue, nous avons renommé la section _Les gens_ en _Les acteurs_. Nous pensons laisser la discoverability dans celle-ci, car nous avons créé cette section pour justement représenter le côté social de Git lorsqu'il est utilisé en public et en ligne.
N'hésitez pas à nous faire d'autres retours si vous pensez qu'il y a d'autres problèmes, nous sommes toujours à l'écoute de notre communauté
