### ISSUE TITLE
Pourquoi l'open source ? 

### ISSUE THREAD

**Issue by decima** [takk74/OpenSourcePourLesNuls#14]
Dans ce toolkit "pour les nuls" j'expliquerais l'importance de contribuer à l'open-source ? 

Pourquoi on contribue à l'open-source ? Est-ce que c'est réservé à des étudiants dans leur chambre? 
Qui contribue à l'open-source ? 

En clair, c'est cool comme guide, mais faut donner envie aux gens de participer 👍

**Comment by Raphy73** [comment]
Cette section est ajoutée en haut du document.
